"""Export a golden fixture pinning the Go normalization to the Python one.

The Go processor and the Python training code both transform raw Statcast
readings, and they have to agree exactly. If they drift, nothing errors: the
model simply starts receiving features that mean something slightly different
from what it was trained on, and every score quietly stops being meaningful.

This script runs real pitches through the training-time feature code and
writes the inputs alongside the outputs. The Go test reads that file and
requires a match. Regenerating it after changing features.py is the point --
the diff shows what moved, and the Go side has to move with it.

Usage:
    .venv/bin/python ml/scripts/export_normalization_fixture.py
"""

from __future__ import annotations

import json
import logging
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pitchlab_ml import config, features, labels  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(levelname)-5s %(message)s")
log = logging.getLogger("fixture")

OUT_PATH = Path(__file__).resolve().parents[2] / "internal" / "processor" / \
    "testdata" / "normalization_golden.json"

RAW_FIELDS = [
    "release_speed", "release_spin_rate", "spin_axis",
    "release_pos_x", "release_pos_z", "release_extension",
    "pfx_x", "pfx_z", "plate_x", "plate_z", "sz_top", "sz_bot", "arm_angle",
]

DERIVED_FIELDS = [
    "pfx_x_arm", "release_pos_x_arm", "plate_x_bat",
    "zone_height_norm", "in_zone",
    "spin_axis_sin", "spin_axis_cos", "dist_from_zone_center",
]


def value(v):
    """JSON-safe, with missing as null rather than NaN."""
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return None
    if isinstance(v, (np.bool_, bool)):
        return bool(v)
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating, float)):
        return None if math.isnan(float(v)) else float(v)
    return str(v)


def main() -> int:
    snapshots = sorted(config.RAW_DIR.glob("statcast_*.parquet"))
    if not snapshots:
        log.error("no data snapshot; run ml/scripts/pull_seasons.py first")
        return 1

    raw = pd.read_parquet(snapshots[-1], columns=features.required_raw_columns())
    raw = raw[raw["game_year"] == 2025]

    # Cover the cases that actually differ: both pitcher hands, both batter
    # stances, and a pitch in and out of the zone. A fixture of only
    # right-on-right pitches would pass with the mirroring inverted.
    cases: list[pd.DataFrame] = []
    for p_throws in ("R", "L"):
        for stand in ("R", "L"):
            subset = raw[(raw["p_throws"] == p_throws) & (raw["stand"] == stand)]
            if subset.empty:
                continue
            cases.append(subset.head(6))

    # Rows with missing readings, so the null handling is pinned too.
    missing = raw[raw["release_spin_rate"].isna() | raw["plate_x"].isna()]
    if not missing.empty:
        cases.append(missing.head(4))

    sample = pd.concat(cases, ignore_index=True)
    log.info("selected %d pitches", len(sample))

    built = features.build_features(labels.attach_labels(sample))

    records = []
    for i in range(len(built)):
        row = built.iloc[i]
        record = {
            "input": {
                "p_throws": value(row["p_throws"]),
                "stand": value(row["stand"]),
                "pitch_type": value(row["pitch_type"]),
                **{f: value(row[f]) for f in RAW_FIELDS if f in built.columns},
            },
            "expected": {
                f: value(row[f]) for f in DERIVED_FIELDS if f in built.columns
            },
        }
        records.append(record)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps({
        "note": (
            "Generated by ml/scripts/export_normalization_fixture.py. "
            "Pins the Go processor's normalization to the Python training-time "
            "feature code. Regenerate after changing pitchlab_ml/features.py."
        ),
        "source_snapshot": snapshots[-1].name,
        "cases": records,
    }, indent=2) + "\n", encoding="utf-8")

    log.info("wrote %s (%d cases, %.1f KB)",
             OUT_PATH.relative_to(Path.cwd()) if OUT_PATH.is_relative_to(Path.cwd())
             else OUT_PATH,
             len(records), OUT_PATH.stat().st_size / 1024)

    hands = built.groupby(["p_throws", "stand"], observed=True).size()
    log.info("handedness coverage:\n%s", hands.to_string())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
