// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAthletePitchTypeDistribution = `-- name: GetAthletePitchTypeDistribution :many
SELECT
    p.pitch_type,
    max(p.pitch_name)                AS pitch_name,
    count(*)                         AS n,
    avg(m.release_speed)             AS avg_release_speed,
    avg(m.release_spin_rate)         AS avg_release_spin_rate,
    avg(m.pfx_x_arm)                 AS avg_pfx_x_arm,
    avg(m.pfx_z)                     AS avg_pfx_z,
    avg(pr.score)                    AS avg_pitch_score,
    sum(CASE WHEN p.actual_outcome = 'SWINGING_STRIKE' THEN 1 ELSE 0 END)::float
        / NULLIF(sum(CASE WHEN p.actual_outcome IN
            ('SWINGING_STRIKE', 'FOUL', 'IN_PLAY') THEN 1 ELSE 0 END), 0) AS whiff_rate
FROM pitches p
LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
LEFT JOIN pitch_predictions pr ON pr.pitch_id = p.id
     AND pr.model_version_id = (
         SELECT id FROM model_versions WHERE variant = 'pitching' AND is_active LIMIT 1
     )
WHERE p.pitcher_athlete_id = $1
  AND p.pitch_type IS NOT NULL
  AND ($2::timestamptz IS NULL OR p.thrown_at >= $2)
  AND ($3::timestamptz IS NULL OR p.thrown_at <= $3)
GROUP BY p.pitch_type
ORDER BY n DESC
`

type GetAthletePitchTypeDistributionParams struct {
	PitcherAthleteID uuid.UUID
	FromTs           *time.Time
	ToTs             *time.Time
}

type GetAthletePitchTypeDistributionRow struct {
	PitchType          *string
	PitchName          interface{}
	N                  int64
	AvgReleaseSpeed    float64
	AvgReleaseSpinRate float64
	AvgPfxXArm         float64
	AvgPfxZ            float64
	AvgPitchScore      float64
	WhiffRate          int32
}

// Arsenal breakdown. Served by ix_pitches_pitcher_type.
func (q *Queries) GetAthletePitchTypeDistribution(ctx context.Context, arg GetAthletePitchTypeDistributionParams) ([]GetAthletePitchTypeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getAthletePitchTypeDistribution, arg.PitcherAthleteID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAthletePitchTypeDistributionRow{}
	for rows.Next() {
		var i GetAthletePitchTypeDistributionRow
		if err := rows.Scan(
			&i.PitchType,
			&i.PitchName,
			&i.N,
			&i.AvgReleaseSpeed,
			&i.AvgReleaseSpinRate,
			&i.AvgPfxXArm,
			&i.AvgPfxZ,
			&i.AvgPitchScore,
			&i.WhiffRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteSessionTrend = `-- name: GetAthleteSessionTrend :many
SELECT
    s.id                     AS session_id,
    s.source_game_date,
    s.started_at,
    s.pitch_count,
    s.avg_release_speed,
    s.avg_release_spin_rate,
    s.avg_pitch_score
FROM sessions s
WHERE s.pitcher_athlete_id = $1
  AND s.pitch_count > 0
ORDER BY s.started_at DESC
LIMIT $2
`

type GetAthleteSessionTrendParams struct {
	PitcherAthleteID uuid.UUID
	Limit            int32
}

type GetAthleteSessionTrendRow struct {
	SessionID          uuid.UUID
	SourceGameDate     *time.Time
	StartedAt          time.Time
	PitchCount         int32
	AvgReleaseSpeed    *float32
	AvgReleaseSpinRate *float32
	AvgPitchScore      *float32
}

// Per-outing series behind the performance trend chart.
func (q *Queries) GetAthleteSessionTrend(ctx context.Context, arg GetAthleteSessionTrendParams) ([]GetAthleteSessionTrendRow, error) {
	rows, err := q.db.Query(ctx, getAthleteSessionTrend, arg.PitcherAthleteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAthleteSessionTrendRow{}
	for rows.Next() {
		var i GetAthleteSessionTrendRow
		if err := rows.Scan(
			&i.SessionID,
			&i.SourceGameDate,
			&i.StartedAt,
			&i.PitchCount,
			&i.AvgReleaseSpeed,
			&i.AvgReleaseSpinRate,
			&i.AvgPitchScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteSummary = `-- name: GetAthleteSummary :one
SELECT
    count(*)                                       AS pitch_count,
    count(DISTINCT p.session_id)                   AS session_count,
    avg(m.release_speed)                           AS avg_release_speed,
    avg(m.release_spin_rate)                       AS avg_release_spin_rate,
    avg(m.release_extension)                       AS avg_release_extension,
    avg(pr.score)                                  AS avg_pitch_score,
    -- Whiff rate has swings in the denominator, not pitches: it measures how
    -- often a batter misses when he offers.
    sum(CASE WHEN p.actual_outcome = 'SWINGING_STRIKE' THEN 1 ELSE 0 END)::float
        / NULLIF(sum(CASE WHEN p.actual_outcome IN
            ('SWINGING_STRIKE', 'FOUL', 'IN_PLAY') THEN 1 ELSE 0 END), 0)
                                                   AS whiff_rate,
    sum(CASE WHEN p.actual_outcome = 'CALLED_STRIKE' THEN 1 ELSE 0 END)::float
        / NULLIF(count(*), 0)                      AS called_strike_rate,
    sum(CASE WHEN m.in_zone THEN 1 ELSE 0 END)::float
        / NULLIF(count(m.in_zone), 0)              AS in_zone_rate
FROM pitches p
LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
LEFT JOIN pitch_predictions pr ON pr.pitch_id = p.id
     AND pr.model_version_id = (
         SELECT id FROM model_versions WHERE variant = 'pitching' AND is_active LIMIT 1
     )
WHERE p.pitcher_athlete_id = $1
  AND ($2::timestamptz IS NULL OR p.thrown_at >= $2)
  AND ($3::timestamptz IS NULL OR p.thrown_at <= $3)
`

type GetAthleteSummaryParams struct {
	PitcherAthleteID uuid.UUID
	FromTs           *time.Time
	ToTs             *time.Time
}

type GetAthleteSummaryRow struct {
	PitchCount          int64
	SessionCount        int64
	AvgReleaseSpeed     float64
	AvgReleaseSpinRate  float64
	AvgReleaseExtension float64
	AvgPitchScore       float64
	WhiffRate           int32
	CalledStrikeRate    int32
	InZoneRate          int32
}

// The KPI strip on the athlete overview page. Expensive enough to be worth
// caching in Redis; correct enough to be the fallback when the cache is cold
// or unavailable.
func (q *Queries) GetAthleteSummary(ctx context.Context, arg GetAthleteSummaryParams) (GetAthleteSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAthleteSummary, arg.PitcherAthleteID, arg.FromTs, arg.ToTs)
	var i GetAthleteSummaryRow
	err := row.Scan(
		&i.PitchCount,
		&i.SessionCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgReleaseExtension,
		&i.AvgPitchScore,
		&i.WhiffRate,
		&i.CalledStrikeRate,
		&i.InZoneRate,
	)
	return i, err
}
