// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: anomalies.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAnomaly = `-- name: AcknowledgeAnomaly :one
UPDATE performance_anomalies
SET acknowledged_at = now()
WHERE id = $1 AND acknowledged_at IS NULL
RETURNING id, athlete_id, session_id, metric, pitch_type, observed_value, baseline_median, robust_sigma, z_robust, direction, severity, window_sessions, detector_version, detected_at, acknowledged_at
`

// Idempotent: a second call returns no row, which is how the handler
// distinguishes "already acknowledged" from "not found".
func (q *Queries) AcknowledgeAnomaly(ctx context.Context, id uuid.UUID) (PerformanceAnomaly, error) {
	row := q.db.QueryRow(ctx, acknowledgeAnomaly, id)
	var i PerformanceAnomaly
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.SessionID,
		&i.Metric,
		&i.PitchType,
		&i.ObservedValue,
		&i.BaselineMedian,
		&i.RobustSigma,
		&i.ZRobust,
		&i.Direction,
		&i.Severity,
		&i.WindowSessions,
		&i.DetectorVersion,
		&i.DetectedAt,
		&i.AcknowledgedAt,
	)
	return i, err
}

const countOpenAnomalies = `-- name: CountOpenAnomalies :one
SELECT count(*) FROM performance_anomalies
WHERE athlete_id = $1 AND acknowledged_at IS NULL
`

// Served by the partial index ix_anomaly_open.
func (q *Queries) CountOpenAnomalies(ctx context.Context, athleteID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAnomalies, athleteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnomaly = `-- name: GetAnomaly :one
SELECT id, athlete_id, session_id, metric, pitch_type, observed_value, baseline_median, robust_sigma, z_robust, direction, severity, window_sessions, detector_version, detected_at, acknowledged_at FROM performance_anomalies WHERE id = $1
`

func (q *Queries) GetAnomaly(ctx context.Context, id uuid.UUID) (PerformanceAnomaly, error) {
	row := q.db.QueryRow(ctx, getAnomaly, id)
	var i PerformanceAnomaly
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.SessionID,
		&i.Metric,
		&i.PitchType,
		&i.ObservedValue,
		&i.BaselineMedian,
		&i.RobustSigma,
		&i.ZRobust,
		&i.Direction,
		&i.Severity,
		&i.WindowSessions,
		&i.DetectorVersion,
		&i.DetectedAt,
		&i.AcknowledgedAt,
	)
	return i, err
}

const getAnomalyBaselineWindow = `-- name: GetAnomalyBaselineWindow :many
SELECT
    s.id                                    AS session_id,
    s.started_at,
    count(*)                                AS pitch_count,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_speed)     AS median_release_speed,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_spin_rate) AS median_release_spin_rate,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_pos_x_arm) AS median_release_pos_x_arm,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_pos_z)     AS median_release_pos_z,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_extension) AS median_release_extension,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.pfx_x_arm)         AS median_pfx_x_arm,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.pfx_z)             AS median_pfx_z
FROM sessions s
JOIN pitches p            ON p.session_id = s.id
JOIN pitch_measurements m ON m.pitch_id = p.id
WHERE s.pitcher_athlete_id = $1
  AND p.pitch_type = $2
  AND s.started_at < $3::timestamptz
  AND m.measurement_quality <> 'SUSPECT'
GROUP BY s.id, s.started_at
HAVING count(*) >= $4::int
ORDER BY s.started_at DESC
LIMIT $5::int
`

type GetAnomalyBaselineWindowParams struct {
	PitcherAthleteID uuid.UUID
	PitchType        *string
	Before           time.Time
	MinPitches       int32
	WindowSize       int32
}

type GetAnomalyBaselineWindowRow struct {
	SessionID              uuid.UUID
	StartedAt              time.Time
	PitchCount             int64
	MedianReleaseSpeed     float64
	MedianReleaseSpinRate  float64
	MedianReleasePosXArm   float64
	MedianReleasePosZ      float64
	MedianReleaseExtension float64
	MedianPfxXArm          float64
	MedianPfxZ             float64
}

// Trailing per-session medians for one pitcher and pitch type, newest first.
//
// This feeds the robust z-score: median and MAD over the previous N sessions.
// Median rather than mean, and MAD rather than standard deviation, because a
// single injury outing inside the window would otherwise inflate sigma and
// mask every later real anomaly.
// Thin outings are a noisy baseline; better to have fewer, sounder points.
func (q *Queries) GetAnomalyBaselineWindow(ctx context.Context, arg GetAnomalyBaselineWindowParams) ([]GetAnomalyBaselineWindowRow, error) {
	rows, err := q.db.Query(ctx, getAnomalyBaselineWindow,
		arg.PitcherAthleteID,
		arg.PitchType,
		arg.Before,
		arg.MinPitches,
		arg.WindowSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnomalyBaselineWindowRow{}
	for rows.Next() {
		var i GetAnomalyBaselineWindowRow
		if err := rows.Scan(
			&i.SessionID,
			&i.StartedAt,
			&i.PitchCount,
			&i.MedianReleaseSpeed,
			&i.MedianReleaseSpinRate,
			&i.MedianReleasePosXArm,
			&i.MedianReleasePosZ,
			&i.MedianReleaseExtension,
			&i.MedianPfxXArm,
			&i.MedianPfxZ,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionMetricMedians = `-- name: GetSessionMetricMedians :one
SELECT
    count(*)                                AS pitch_count,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_speed)     AS median_release_speed,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_spin_rate) AS median_release_spin_rate,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_pos_x_arm) AS median_release_pos_x_arm,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_pos_z)     AS median_release_pos_z,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.release_extension) AS median_release_extension,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.pfx_x_arm)         AS median_pfx_x_arm,
    percentile_cont(0.5) WITHIN GROUP (ORDER BY m.pfx_z)             AS median_pfx_z
FROM pitches p
JOIN pitch_measurements m ON m.pitch_id = p.id
WHERE p.session_id = $1
  AND p.pitch_type = $2
  AND m.measurement_quality <> 'SUSPECT'
`

type GetSessionMetricMediansParams struct {
	SessionID uuid.UUID
	PitchType *string
}

type GetSessionMetricMediansRow struct {
	PitchCount             int64
	MedianReleaseSpeed     float64
	MedianReleaseSpinRate  float64
	MedianReleasePosXArm   float64
	MedianReleasePosZ      float64
	MedianReleaseExtension float64
	MedianPfxXArm          float64
	MedianPfxZ             float64
}

// The session under evaluation, shaped like one row of the baseline window.
func (q *Queries) GetSessionMetricMedians(ctx context.Context, arg GetSessionMetricMediansParams) (GetSessionMetricMediansRow, error) {
	row := q.db.QueryRow(ctx, getSessionMetricMedians, arg.SessionID, arg.PitchType)
	var i GetSessionMetricMediansRow
	err := row.Scan(
		&i.PitchCount,
		&i.MedianReleaseSpeed,
		&i.MedianReleaseSpinRate,
		&i.MedianReleasePosXArm,
		&i.MedianReleasePosZ,
		&i.MedianReleaseExtension,
		&i.MedianPfxXArm,
		&i.MedianPfxZ,
	)
	return i, err
}

const insertAnomaly = `-- name: InsertAnomaly :one
INSERT INTO performance_anomalies (
    id, athlete_id, session_id, metric, pitch_type,
    observed_value, baseline_median, robust_sigma, z_robust,
    direction, severity, window_sessions, detector_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (session_id, metric, COALESCE(pitch_type, ''), detector_version)
DO NOTHING
RETURNING id, athlete_id, session_id, metric, pitch_type, observed_value, baseline_median, robust_sigma, z_robust, direction, severity, window_sessions, detector_version, detected_at, acknowledged_at
`

type InsertAnomalyParams struct {
	ID              uuid.UUID
	AthleteID       uuid.UUID
	SessionID       uuid.UUID
	Metric          string
	PitchType       *string
	ObservedValue   float32
	BaselineMedian  float32
	RobustSigma     float32
	ZRobust         float32
	Direction       string
	Severity        string
	WindowSessions  int16
	DetectorVersion string
}

// Idempotent via the unique index on
// (session_id, metric, COALESCE(pitch_type, ”), detector_version).
// COALESCE is not cosmetic: NULL <> NULL in a plain unique constraint, so
// without it the rows that most need protection -- those with no pitch type --
// would duplicate freely on a re-consumed event.
func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) (PerformanceAnomaly, error) {
	row := q.db.QueryRow(ctx, insertAnomaly,
		arg.ID,
		arg.AthleteID,
		arg.SessionID,
		arg.Metric,
		arg.PitchType,
		arg.ObservedValue,
		arg.BaselineMedian,
		arg.RobustSigma,
		arg.ZRobust,
		arg.Direction,
		arg.Severity,
		arg.WindowSessions,
		arg.DetectorVersion,
	)
	var i PerformanceAnomaly
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.SessionID,
		&i.Metric,
		&i.PitchType,
		&i.ObservedValue,
		&i.BaselineMedian,
		&i.RobustSigma,
		&i.ZRobust,
		&i.Direction,
		&i.Severity,
		&i.WindowSessions,
		&i.DetectorVersion,
		&i.DetectedAt,
		&i.AcknowledgedAt,
	)
	return i, err
}

const listAnomaliesByAthlete = `-- name: ListAnomaliesByAthlete :many
SELECT id, athlete_id, session_id, metric, pitch_type, observed_value, baseline_median, robust_sigma, z_robust, direction, severity, window_sessions, detector_version, detected_at, acknowledged_at FROM performance_anomalies
WHERE athlete_id = $1
  AND ($3::text IS NULL OR severity = $3)
  AND ($4::text IS NULL OR metric = $4)
  AND (
      $5::bool IS NULL
      OR ($5::bool AND acknowledged_at IS NOT NULL)
      OR (NOT $5::bool AND acknowledged_at IS NULL)
  )
  AND ($6::timestamptz IS NULL
       OR (detected_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY detected_at DESC, id DESC
LIMIT $2
`

type ListAnomaliesByAthleteParams struct {
	AthleteID      uuid.UUID
	Limit          int32
	Severity       *string
	Metric         *string
	Acknowledged   *bool
	CursorDetected *time.Time
	CursorID       *uuid.UUID
}

func (q *Queries) ListAnomaliesByAthlete(ctx context.Context, arg ListAnomaliesByAthleteParams) ([]PerformanceAnomaly, error) {
	rows, err := q.db.Query(ctx, listAnomaliesByAthlete,
		arg.AthleteID,
		arg.Limit,
		arg.Severity,
		arg.Metric,
		arg.Acknowledged,
		arg.CursorDetected,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformanceAnomaly{}
	for rows.Next() {
		var i PerformanceAnomaly
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.SessionID,
			&i.Metric,
			&i.PitchType,
			&i.ObservedValue,
			&i.BaselineMedian,
			&i.RobustSigma,
			&i.ZRobust,
			&i.Direction,
			&i.Severity,
			&i.WindowSessions,
			&i.DetectorVersion,
			&i.DetectedAt,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnomaliesBySession = `-- name: ListAnomaliesBySession :many
SELECT id, athlete_id, session_id, metric, pitch_type, observed_value, baseline_median, robust_sigma, z_robust, direction, severity, window_sessions, detector_version, detected_at, acknowledged_at FROM performance_anomalies
WHERE session_id = $1
ORDER BY detected_at DESC
`

func (q *Queries) ListAnomaliesBySession(ctx context.Context, sessionID uuid.UUID) ([]PerformanceAnomaly, error) {
	rows, err := q.db.Query(ctx, listAnomaliesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformanceAnomaly{}
	for rows.Next() {
		var i PerformanceAnomaly
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.SessionID,
			&i.Metric,
			&i.PitchType,
			&i.ObservedValue,
			&i.BaselineMedian,
			&i.RobustSigma,
			&i.ZRobust,
			&i.Direction,
			&i.Severity,
			&i.WindowSessions,
			&i.DetectorVersion,
			&i.DetectedAt,
			&i.AcknowledgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
