// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: athletes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAthlete = `-- name: GetAthlete :one
SELECT id, mlbam_id, full_name, throws, bats, primary_role, birth_date, created_at, updated_at FROM athletes WHERE id = $1
`

func (q *Queries) GetAthlete(ctx context.Context, id uuid.UUID) (Athlete, error) {
	row := q.db.QueryRow(ctx, getAthlete, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.MlbamID,
		&i.FullName,
		&i.Throws,
		&i.Bats,
		&i.PrimaryRole,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAthleteByMLBAMID = `-- name: GetAthleteByMLBAMID :one
SELECT id, mlbam_id, full_name, throws, bats, primary_role, birth_date, created_at, updated_at FROM athletes WHERE mlbam_id = $1
`

func (q *Queries) GetAthleteByMLBAMID(ctx context.Context, mlbamID int32) (Athlete, error) {
	row := q.db.QueryRow(ctx, getAthleteByMLBAMID, mlbamID)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.MlbamID,
		&i.FullName,
		&i.Throws,
		&i.Bats,
		&i.PrimaryRole,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAthleteTotals = `-- name: GetAthleteTotals :one
SELECT
    (SELECT count(*) FROM sessions s WHERE s.pitcher_athlete_id = $1) AS session_count,
    (SELECT count(*) FROM pitches p  WHERE p.pitcher_athlete_id = $1) AS pitch_count,
    (SELECT min(p.thrown_at) FROM pitches p WHERE p.pitcher_athlete_id = $1) AS first_pitch_at,
    (SELECT max(p.thrown_at) FROM pitches p WHERE p.pitcher_athlete_id = $1) AS last_pitch_at
`

type GetAthleteTotalsRow struct {
	SessionCount int64
	PitchCount   int64
	FirstPitchAt interface{}
	LastPitchAt  interface{}
}

func (q *Queries) GetAthleteTotals(ctx context.Context, pitcherAthleteID uuid.UUID) (GetAthleteTotalsRow, error) {
	row := q.db.QueryRow(ctx, getAthleteTotals, pitcherAthleteID)
	var i GetAthleteTotalsRow
	err := row.Scan(
		&i.SessionCount,
		&i.PitchCount,
		&i.FirstPitchAt,
		&i.LastPitchAt,
	)
	return i, err
}

const listAthletes = `-- name: ListAthletes :many
SELECT a.id, a.mlbam_id, a.full_name, a.throws, a.bats, a.primary_role, a.birth_date, a.created_at, a.updated_at,
       (SELECT count(*) FROM sessions s WHERE s.pitcher_athlete_id = a.id) AS session_count,
       (SELECT count(*) FROM pitches p WHERE p.pitcher_athlete_id = a.id)  AS pitch_count
FROM athletes a
WHERE ($2::text IS NULL OR a.full_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR a.primary_role = $3)
  AND ($4::text IS NULL OR a.throws = $4)
  AND (
      $5::text IS NULL
      OR (a.full_name, a.id) > ($5::text, $6::uuid)
  )
ORDER BY a.full_name, a.id
LIMIT $1
`

type ListAthletesParams struct {
	Limit      int32
	Search     *string
	Role       *string
	Throws     *string
	CursorName *string
	CursorID   *uuid.UUID
}

type ListAthletesRow struct {
	ID           uuid.UUID
	MlbamID      int32
	FullName     string
	Throws       *string
	Bats         *string
	PrimaryRole  string
	BirthDate    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	SessionCount int64
	PitchCount   int64
}

// Keyset pagination on (full_name, id): offsets shift as rows are inserted,
// which would repeat or skip records in a continuously growing table.
func (q *Queries) ListAthletes(ctx context.Context, arg ListAthletesParams) ([]ListAthletesRow, error) {
	rows, err := q.db.Query(ctx, listAthletes,
		arg.Limit,
		arg.Search,
		arg.Role,
		arg.Throws,
		arg.CursorName,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAthletesRow{}
	for rows.Next() {
		var i ListAthletesRow
		if err := rows.Scan(
			&i.ID,
			&i.MlbamID,
			&i.FullName,
			&i.Throws,
			&i.Bats,
			&i.PrimaryRole,
			&i.BirthDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionCount,
			&i.PitchCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAthlete = `-- name: UpsertAthlete :one
INSERT INTO athletes (
    id, mlbam_id, full_name, throws, bats, primary_role, birth_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (mlbam_id) DO UPDATE SET
    full_name    = EXCLUDED.full_name,
    throws       = COALESCE(EXCLUDED.throws, athletes.throws),
    bats         = COALESCE(EXCLUDED.bats, athletes.bats),
    primary_role = CASE
        WHEN athletes.primary_role = 'UNKNOWN' THEN EXCLUDED.primary_role
        WHEN athletes.primary_role <> EXCLUDED.primary_role
             AND EXCLUDED.primary_role <> 'UNKNOWN' THEN 'TWO_WAY'
        ELSE athletes.primary_role
    END,
    birth_date   = COALESCE(EXCLUDED.birth_date, athletes.birth_date),
    updated_at   = now()
RETURNING id, mlbam_id, full_name, throws, bats, primary_role, birth_date, created_at, updated_at
`

type UpsertAthleteParams struct {
	ID          uuid.UUID
	MlbamID     int32
	FullName    string
	Throws      *string
	Bats        *string
	PrimaryRole string
	BirthDate   *time.Time
}

// Idempotent by mlbam_id. The event stream re-announces the same athlete on
// every pitch, so this must converge rather than accumulate. Name and
// handedness are refreshed; created_at is not touched.
func (q *Queries) UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) (Athlete, error) {
	row := q.db.QueryRow(ctx, upsertAthlete,
		arg.ID,
		arg.MlbamID,
		arg.FullName,
		arg.Throws,
		arg.Bats,
		arg.PrimaryRole,
		arg.BirthDate,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.MlbamID,
		&i.FullName,
		&i.Throws,
		&i.Bats,
		&i.PrimaryRole,
		&i.BirthDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
