// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getDeviceByKey = `-- name: GetDeviceByKey :one
SELECT id, device_key, device_kind, display_name, calibration_profile, created_at FROM devices WHERE device_key = $1
`

func (q *Queries) GetDeviceByKey(ctx context.Context, deviceKey string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByKey, deviceKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceKey,
		&i.DeviceKind,
		&i.DisplayName,
		&i.CalibrationProfile,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, device_key, device_kind, display_name, calibration_profile, created_at FROM devices ORDER BY device_key
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceKey,
			&i.DeviceKind,
			&i.DisplayName,
			&i.CalibrationProfile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (id, device_key, device_kind, display_name, calibration_profile)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (device_key) DO UPDATE SET
    device_kind         = EXCLUDED.device_kind,
    display_name        = COALESCE(EXCLUDED.display_name, devices.display_name),
    calibration_profile = EXCLUDED.calibration_profile
RETURNING id, device_key, device_kind, display_name, calibration_profile, created_at
`

type UpsertDeviceParams struct {
	ID                 uuid.UUID
	DeviceKey          string
	DeviceKind         string
	DisplayName        *string
	CalibrationProfile []byte
}

// Idempotent by device_key. The replay simulator registers itself on every
// run, which is how simulated rows stay distinguishable from real ones.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.ID,
		arg.DeviceKey,
		arg.DeviceKind,
		arg.DisplayName,
		arg.CalibrationProfile,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceKey,
		&i.DeviceKind,
		&i.DisplayName,
		&i.CalibrationProfile,
		&i.CreatedAt,
	)
	return i, err
}
