// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: measurements.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countMeasurementsByNormalizationVersion = `-- name: CountMeasurementsByNormalizationVersion :many
SELECT normalization_version, count(*) AS n
FROM pitch_measurements
GROUP BY normalization_version
ORDER BY normalization_version
`

type CountMeasurementsByNormalizationVersionRow struct {
	NormalizationVersion int16
	N                    int64
}

// Tells you whether a re-normalization pass finished, or left the table
// holding two conventions at once.
func (q *Queries) CountMeasurementsByNormalizationVersion(ctx context.Context) ([]CountMeasurementsByNormalizationVersionRow, error) {
	rows, err := q.db.Query(ctx, countMeasurementsByNormalizationVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountMeasurementsByNormalizationVersionRow{}
	for rows.Next() {
		var i CountMeasurementsByNormalizationVersionRow
		if err := rows.Scan(&i.NormalizationVersion, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPitchMeasurement = `-- name: GetPitchMeasurement :one
SELECT pitch_id, device_id, release_speed, release_spin_rate, spin_axis, release_pos_x, release_pos_y, release_pos_z, release_extension, pfx_x, pfx_z, plate_x, plate_z, sz_top, sz_bot, effective_speed, arm_angle, pfx_x_arm, release_pos_x_arm, plate_x_bat, zone_height_norm, in_zone, normalization_version, measurement_quality, created_at FROM pitch_measurements WHERE pitch_id = $1
`

func (q *Queries) GetPitchMeasurement(ctx context.Context, pitchID uuid.UUID) (PitchMeasurement, error) {
	row := q.db.QueryRow(ctx, getPitchMeasurement, pitchID)
	var i PitchMeasurement
	err := row.Scan(
		&i.PitchID,
		&i.DeviceID,
		&i.ReleaseSpeed,
		&i.ReleaseSpinRate,
		&i.SpinAxis,
		&i.ReleasePosX,
		&i.ReleasePosY,
		&i.ReleasePosZ,
		&i.ReleaseExtension,
		&i.PfxX,
		&i.PfxZ,
		&i.PlateX,
		&i.PlateZ,
		&i.SzTop,
		&i.SzBot,
		&i.EffectiveSpeed,
		&i.ArmAngle,
		&i.PfxXArm,
		&i.ReleasePosXArm,
		&i.PlateXBat,
		&i.ZoneHeightNorm,
		&i.InZone,
		&i.NormalizationVersion,
		&i.MeasurementQuality,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPitchMeasurement = `-- name: UpsertPitchMeasurement :one
INSERT INTO pitch_measurements (
    pitch_id, device_id,
    release_speed, release_spin_rate, spin_axis,
    release_pos_x, release_pos_y, release_pos_z, release_extension,
    pfx_x, pfx_z, plate_x, plate_z, sz_top, sz_bot,
    effective_speed, arm_angle,
    pfx_x_arm, release_pos_x_arm, plate_x_bat, zone_height_norm, in_zone,
    normalization_version, measurement_quality
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22, $23, $24
)
ON CONFLICT (pitch_id) DO UPDATE SET
    device_id             = EXCLUDED.device_id,
    release_speed         = EXCLUDED.release_speed,
    release_spin_rate     = EXCLUDED.release_spin_rate,
    spin_axis             = EXCLUDED.spin_axis,
    release_pos_x         = EXCLUDED.release_pos_x,
    release_pos_y         = EXCLUDED.release_pos_y,
    release_pos_z         = EXCLUDED.release_pos_z,
    release_extension     = EXCLUDED.release_extension,
    pfx_x                 = EXCLUDED.pfx_x,
    pfx_z                 = EXCLUDED.pfx_z,
    plate_x               = EXCLUDED.plate_x,
    plate_z               = EXCLUDED.plate_z,
    sz_top                = EXCLUDED.sz_top,
    sz_bot                = EXCLUDED.sz_bot,
    effective_speed       = EXCLUDED.effective_speed,
    arm_angle             = EXCLUDED.arm_angle,
    pfx_x_arm             = EXCLUDED.pfx_x_arm,
    release_pos_x_arm     = EXCLUDED.release_pos_x_arm,
    plate_x_bat           = EXCLUDED.plate_x_bat,
    zone_height_norm      = EXCLUDED.zone_height_norm,
    in_zone               = EXCLUDED.in_zone,
    normalization_version = EXCLUDED.normalization_version,
    measurement_quality   = EXCLUDED.measurement_quality
RETURNING pitch_id, device_id, release_speed, release_spin_rate, spin_axis, release_pos_x, release_pos_y, release_pos_z, release_extension, pfx_x, pfx_z, plate_x, plate_z, sz_top, sz_bot, effective_speed, arm_angle, pfx_x_arm, release_pos_x_arm, plate_x_bat, zone_height_norm, in_zone, normalization_version, measurement_quality, created_at
`

type UpsertPitchMeasurementParams struct {
	PitchID              uuid.UUID
	DeviceID             *uuid.UUID
	ReleaseSpeed         *float32
	ReleaseSpinRate      *float32
	SpinAxis             *float32
	ReleasePosX          *float32
	ReleasePosY          *float32
	ReleasePosZ          *float32
	ReleaseExtension     *float32
	PfxX                 *float32
	PfxZ                 *float32
	PlateX               *float32
	PlateZ               *float32
	SzTop                *float32
	SzBot                *float32
	EffectiveSpeed       *float32
	ArmAngle             *float32
	PfxXArm              *float32
	ReleasePosXArm       *float32
	PlateXBat            *float32
	ZoneHeightNorm       *float32
	InZone               *bool
	NormalizationVersion int16
	MeasurementQuality   string
}

// Keyed on pitch_id, so re-processing a pitch replaces its measurement rather
// than duplicating it. The update path is also what a re-normalization pass
// uses: it rewrites the derived columns and bumps normalization_version
// without touching the pitch's context row.
func (q *Queries) UpsertPitchMeasurement(ctx context.Context, arg UpsertPitchMeasurementParams) (PitchMeasurement, error) {
	row := q.db.QueryRow(ctx, upsertPitchMeasurement,
		arg.PitchID,
		arg.DeviceID,
		arg.ReleaseSpeed,
		arg.ReleaseSpinRate,
		arg.SpinAxis,
		arg.ReleasePosX,
		arg.ReleasePosY,
		arg.ReleasePosZ,
		arg.ReleaseExtension,
		arg.PfxX,
		arg.PfxZ,
		arg.PlateX,
		arg.PlateZ,
		arg.SzTop,
		arg.SzBot,
		arg.EffectiveSpeed,
		arg.ArmAngle,
		arg.PfxXArm,
		arg.ReleasePosXArm,
		arg.PlateXBat,
		arg.ZoneHeightNorm,
		arg.InZone,
		arg.NormalizationVersion,
		arg.MeasurementQuality,
	)
	var i PitchMeasurement
	err := row.Scan(
		&i.PitchID,
		&i.DeviceID,
		&i.ReleaseSpeed,
		&i.ReleaseSpinRate,
		&i.SpinAxis,
		&i.ReleasePosX,
		&i.ReleasePosY,
		&i.ReleasePosZ,
		&i.ReleaseExtension,
		&i.PfxX,
		&i.PfxZ,
		&i.PlateX,
		&i.PlateZ,
		&i.SzTop,
		&i.SzBot,
		&i.EffectiveSpeed,
		&i.ArmAngle,
		&i.PfxXArm,
		&i.ReleasePosXArm,
		&i.PlateXBat,
		&i.ZoneHeightNorm,
		&i.InZone,
		&i.NormalizationVersion,
		&i.MeasurementQuality,
		&i.CreatedAt,
	)
	return i, err
}
