// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Athlete struct {
	ID       uuid.UUID
	MlbamID  int32
	FullName string
	Throws   *string
	Bats     *string
	// Presentation hint only. The authoritative role is the FK used on pitches.
	PrimaryRole string
	BirthDate   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Device struct {
	ID                 uuid.UUID
	DeviceKey          string
	DeviceKind         string
	DisplayName        *string
	CalibrationProfile []byte
	CreatedAt          time.Time
}

type ModelVersion struct {
	ID               uuid.UUID
	Version          string
	Variant          string
	Target           string
	Algorithm        string
	FeatureColumns   []byte
	ClassLabels      []byte
	RunValueTable    []byte
	ScoreMu          float32
	ScoreSigma       float32
	TrainPeriodStart time.Time
	TrainPeriodEnd   time.Time
	ValPeriodStart   *time.Time
	ValPeriodEnd     *time.Time
	TestPeriodStart  *time.Time
	TestPeriodEnd    *time.Time
	DataSnapshot     string
	GitSha           *string
	Metrics          []byte
	IsActive         bool
	CreatedAt        time.Time
}

type PerformanceAnomaly struct {
	ID              uuid.UUID
	AthleteID       uuid.UUID
	SessionID       uuid.UUID
	Metric          string
	PitchType       *string
	ObservedValue   float32
	BaselineMedian  float32
	RobustSigma     float32
	ZRobust         float32
	Direction       string
	Severity        string
	WindowSessions  int16
	DetectorVersion string
	DetectedAt      time.Time
	AcknowledgedAt  *time.Time
}

type Pitch struct {
	ID                uuid.UUID
	ExternalPitchUid  string
	SessionID         uuid.UUID
	PitcherAthleteID  uuid.UUID
	BatterAthleteID   *uuid.UUID
	AtBatNumber       int16
	PitchNumber       int16
	SessionPitchIndex int32
	ThrownAt          time.Time
	Balls             int16
	Strikes           int16
	OutsWhenUp        int16
	Inning            int16
	InningTopbot      *string
	Stand             string
	PThrows           string
	On1b              bool
	On2b              bool
	On3b              bool
	BatScore          *int16
	FldScore          *int16
	NThruorderPitcher *int16
	PitchType         *string
	PitchName         *string
	// Ground truth for prediction-vs-reality display and model monitoring. Never a model feature.
	ActualOutcome    *string
	PredictionStatus string
	CorrelationID    *uuid.UUID
	SourceEventID    *uuid.UUID
	CreatedAt        time.Time
}

type PitchMeasurement struct {
	PitchID              uuid.UUID
	DeviceID             *uuid.UUID
	ReleaseSpeed         *float32
	ReleaseSpinRate      *float32
	SpinAxis             *float32
	ReleasePosX          *float32
	ReleasePosY          *float32
	ReleasePosZ          *float32
	ReleaseExtension     *float32
	PfxX                 *float32
	PfxZ                 *float32
	PlateX               *float32
	PlateZ               *float32
	SzTop                *float32
	SzBot                *float32
	EffectiveSpeed       *float32
	ArmAngle             *float32
	PfxXArm              *float32
	ReleasePosXArm       *float32
	PlateXBat            *float32
	ZoneHeightNorm       *float32
	InZone               *bool
	NormalizationVersion int16
	MeasurementQuality   string
	CreatedAt            time.Time
}

type PitchPrediction struct {
	ID               uuid.UUID
	PitchID          uuid.UUID
	ModelVersionID   uuid.UUID
	Probabilities    []byte
	PredictedClass   *string
	WhiffProbability *float32
	ScoredQuantity   float32
	Score            float32
	InferenceMs      *float32
	CreatedAt        time.Time
}

type Session struct {
	ID                 uuid.UUID
	ExternalSessionUid string
	PitcherAthleteID   uuid.UUID
	DeviceID           *uuid.UUID
	ExternalGameRef    *string
	SourceGameDate     *time.Time
	OpponentTeam       *string
	StartedAt          time.Time
	EndedAt            *time.Time
	Status             string
	IsSynthetic        bool
	PitchCount         int32
	AvgReleaseSpeed    *float32
	AvgReleaseSpinRate *float32
	AvgPitchScore      *float32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
