// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pitches.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findPitchByCorrelationID = `-- name: FindPitchByCorrelationID :many
SELECT id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id, at_bat_number, pitch_number, session_pitch_index, thrown_at, balls, strikes, outs_when_up, inning, inning_topbot, stand, p_throws, on_1b, on_2b, on_3b, bat_score, fld_score, n_thruorder_pitcher, pitch_type, pitch_name, actual_outcome, prediction_status, correlation_id, source_event_id, created_at FROM pitches WHERE correlation_id = $1 ORDER BY session_pitch_index
`

// Tracing support: resolve a correlation id seen in logs back to the pitch.
func (q *Queries) FindPitchByCorrelationID(ctx context.Context, correlationID *uuid.UUID) ([]Pitch, error) {
	rows, err := q.db.Query(ctx, findPitchByCorrelationID, correlationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pitch{}
	for rows.Next() {
		var i Pitch
		if err := rows.Scan(
			&i.ID,
			&i.ExternalPitchUid,
			&i.SessionID,
			&i.PitcherAthleteID,
			&i.BatterAthleteID,
			&i.AtBatNumber,
			&i.PitchNumber,
			&i.SessionPitchIndex,
			&i.ThrownAt,
			&i.Balls,
			&i.Strikes,
			&i.OutsWhenUp,
			&i.Inning,
			&i.InningTopbot,
			&i.Stand,
			&i.PThrows,
			&i.On1b,
			&i.On2b,
			&i.On3b,
			&i.BatScore,
			&i.FldScore,
			&i.NThruorderPitcher,
			&i.PitchType,
			&i.PitchName,
			&i.ActualOutcome,
			&i.PredictionStatus,
			&i.CorrelationID,
			&i.SourceEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPitch = `-- name: GetPitch :one
SELECT id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id, at_bat_number, pitch_number, session_pitch_index, thrown_at, balls, strikes, outs_when_up, inning, inning_topbot, stand, p_throws, on_1b, on_2b, on_3b, bat_score, fld_score, n_thruorder_pitcher, pitch_type, pitch_name, actual_outcome, prediction_status, correlation_id, source_event_id, created_at FROM pitches WHERE id = $1
`

func (q *Queries) GetPitch(ctx context.Context, id uuid.UUID) (Pitch, error) {
	row := q.db.QueryRow(ctx, getPitch, id)
	var i Pitch
	err := row.Scan(
		&i.ID,
		&i.ExternalPitchUid,
		&i.SessionID,
		&i.PitcherAthleteID,
		&i.BatterAthleteID,
		&i.AtBatNumber,
		&i.PitchNumber,
		&i.SessionPitchIndex,
		&i.ThrownAt,
		&i.Balls,
		&i.Strikes,
		&i.OutsWhenUp,
		&i.Inning,
		&i.InningTopbot,
		&i.Stand,
		&i.PThrows,
		&i.On1b,
		&i.On2b,
		&i.On3b,
		&i.BatScore,
		&i.FldScore,
		&i.NThruorderPitcher,
		&i.PitchType,
		&i.PitchName,
		&i.ActualOutcome,
		&i.PredictionStatus,
		&i.CorrelationID,
		&i.SourceEventID,
		&i.CreatedAt,
	)
	return i, err
}

const getPitchByExternalUID = `-- name: GetPitchByExternalUID :one
SELECT id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id, at_bat_number, pitch_number, session_pitch_index, thrown_at, balls, strikes, outs_when_up, inning, inning_topbot, stand, p_throws, on_1b, on_2b, on_3b, bat_score, fld_score, n_thruorder_pitcher, pitch_type, pitch_name, actual_outcome, prediction_status, correlation_id, source_event_id, created_at FROM pitches WHERE external_pitch_uid = $1
`

func (q *Queries) GetPitchByExternalUID(ctx context.Context, externalPitchUid string) (Pitch, error) {
	row := q.db.QueryRow(ctx, getPitchByExternalUID, externalPitchUid)
	var i Pitch
	err := row.Scan(
		&i.ID,
		&i.ExternalPitchUid,
		&i.SessionID,
		&i.PitcherAthleteID,
		&i.BatterAthleteID,
		&i.AtBatNumber,
		&i.PitchNumber,
		&i.SessionPitchIndex,
		&i.ThrownAt,
		&i.Balls,
		&i.Strikes,
		&i.OutsWhenUp,
		&i.Inning,
		&i.InningTopbot,
		&i.Stand,
		&i.PThrows,
		&i.On1b,
		&i.On2b,
		&i.On3b,
		&i.BatScore,
		&i.FldScore,
		&i.NThruorderPitcher,
		&i.PitchType,
		&i.PitchName,
		&i.ActualOutcome,
		&i.PredictionStatus,
		&i.CorrelationID,
		&i.SourceEventID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPitch = `-- name: InsertPitch :one
INSERT INTO pitches (
    id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id,
    at_bat_number, pitch_number, session_pitch_index, thrown_at,
    balls, strikes, outs_when_up, inning, inning_topbot,
    stand, p_throws, on_1b, on_2b, on_3b,
    bat_score, fld_score, n_thruorder_pitcher,
    pitch_type, pitch_name, actual_outcome, prediction_status,
    correlation_id, source_event_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28
)
ON CONFLICT (external_pitch_uid) DO NOTHING
RETURNING id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id, at_bat_number, pitch_number, session_pitch_index, thrown_at, balls, strikes, outs_when_up, inning, inning_topbot, stand, p_throws, on_1b, on_2b, on_3b, bat_score, fld_score, n_thruorder_pitcher, pitch_type, pitch_name, actual_outcome, prediction_status, correlation_id, source_event_id, created_at
`

type InsertPitchParams struct {
	ID                uuid.UUID
	ExternalPitchUid  string
	SessionID         uuid.UUID
	PitcherAthleteID  uuid.UUID
	BatterAthleteID   *uuid.UUID
	AtBatNumber       int16
	PitchNumber       int16
	SessionPitchIndex int32
	ThrownAt          time.Time
	Balls             int16
	Strikes           int16
	OutsWhenUp        int16
	Inning            int16
	InningTopbot      *string
	Stand             string
	PThrows           string
	On1b              bool
	On2b              bool
	On3b              bool
	BatScore          *int16
	FldScore          *int16
	NThruorderPitcher *int16
	PitchType         *string
	PitchName         *string
	ActualOutcome     *string
	PredictionStatus  string
	CorrelationID     *uuid.UUID
	SourceEventID     *uuid.UUID
}

// The idempotency boundary of the whole pipeline.
//
// Kafka delivers at least once, so this insert will see the same pitch twice
// whenever a consumer dies between doing its work and committing its offset.
// DO NOTHING plus the unique constraint on external_pitch_uid makes that
// harmless, and returning no row is how the caller learns it was a duplicate.
//
// An application-level select-then-insert would race between processor
// instances; the constraint is atomic regardless of concurrency.
func (q *Queries) InsertPitch(ctx context.Context, arg InsertPitchParams) (Pitch, error) {
	row := q.db.QueryRow(ctx, insertPitch,
		arg.ID,
		arg.ExternalPitchUid,
		arg.SessionID,
		arg.PitcherAthleteID,
		arg.BatterAthleteID,
		arg.AtBatNumber,
		arg.PitchNumber,
		arg.SessionPitchIndex,
		arg.ThrownAt,
		arg.Balls,
		arg.Strikes,
		arg.OutsWhenUp,
		arg.Inning,
		arg.InningTopbot,
		arg.Stand,
		arg.PThrows,
		arg.On1b,
		arg.On2b,
		arg.On3b,
		arg.BatScore,
		arg.FldScore,
		arg.NThruorderPitcher,
		arg.PitchType,
		arg.PitchName,
		arg.ActualOutcome,
		arg.PredictionStatus,
		arg.CorrelationID,
		arg.SourceEventID,
	)
	var i Pitch
	err := row.Scan(
		&i.ID,
		&i.ExternalPitchUid,
		&i.SessionID,
		&i.PitcherAthleteID,
		&i.BatterAthleteID,
		&i.AtBatNumber,
		&i.PitchNumber,
		&i.SessionPitchIndex,
		&i.ThrownAt,
		&i.Balls,
		&i.Strikes,
		&i.OutsWhenUp,
		&i.Inning,
		&i.InningTopbot,
		&i.Stand,
		&i.PThrows,
		&i.On1b,
		&i.On2b,
		&i.On3b,
		&i.BatScore,
		&i.FldScore,
		&i.NThruorderPitcher,
		&i.PitchType,
		&i.PitchName,
		&i.ActualOutcome,
		&i.PredictionStatus,
		&i.CorrelationID,
		&i.SourceEventID,
		&i.CreatedAt,
	)
	return i, err
}

const listFailedPredictionPitches = `-- name: ListFailedPredictionPitches :many
SELECT id, external_pitch_uid, session_id, pitcher_athlete_id, batter_athlete_id, at_bat_number, pitch_number, session_pitch_index, thrown_at, balls, strikes, outs_when_up, inning, inning_topbot, stand, p_throws, on_1b, on_2b, on_3b, bat_score, fld_score, n_thruorder_pitcher, pitch_type, pitch_name, actual_outcome, prediction_status, correlation_id, source_event_id, created_at FROM pitches
WHERE prediction_status = 'FAILED'
ORDER BY thrown_at
LIMIT $1
`

// Backfill after an ML outage. Served by the partial index
// ix_pitches_pred_failed, which is negligible in size because these rows are
// expected to be a fraction of a percent.
func (q *Queries) ListFailedPredictionPitches(ctx context.Context, limit int32) ([]Pitch, error) {
	rows, err := q.db.Query(ctx, listFailedPredictionPitches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pitch{}
	for rows.Next() {
		var i Pitch
		if err := rows.Scan(
			&i.ID,
			&i.ExternalPitchUid,
			&i.SessionID,
			&i.PitcherAthleteID,
			&i.BatterAthleteID,
			&i.AtBatNumber,
			&i.PitchNumber,
			&i.SessionPitchIndex,
			&i.ThrownAt,
			&i.Balls,
			&i.Strikes,
			&i.OutsWhenUp,
			&i.Inning,
			&i.InningTopbot,
			&i.Stand,
			&i.PThrows,
			&i.On1b,
			&i.On2b,
			&i.On3b,
			&i.BatScore,
			&i.FldScore,
			&i.NThruorderPitcher,
			&i.PitchType,
			&i.PitchName,
			&i.ActualOutcome,
			&i.PredictionStatus,
			&i.CorrelationID,
			&i.SourceEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPitchesByPitcher = `-- name: ListPitchesByPitcher :many
SELECT
    p.id, p.external_pitch_uid, p.session_id, p.pitcher_athlete_id, p.batter_athlete_id, p.at_bat_number, p.pitch_number, p.session_pitch_index, p.thrown_at, p.balls, p.strikes, p.outs_when_up, p.inning, p.inning_topbot, p.stand, p.p_throws, p.on_1b, p.on_2b, p.on_3b, p.bat_score, p.fld_score, p.n_thruorder_pitcher, p.pitch_type, p.pitch_name, p.actual_outcome, p.prediction_status, p.correlation_id, p.source_event_id, p.created_at,
    m.pitch_id, m.device_id, m.release_speed, m.release_spin_rate, m.spin_axis, m.release_pos_x, m.release_pos_y, m.release_pos_z, m.release_extension, m.pfx_x, m.pfx_z, m.plate_x, m.plate_z, m.sz_top, m.sz_bot, m.effective_speed, m.arm_angle, m.pfx_x_arm, m.release_pos_x_arm, m.plate_x_bat, m.zone_height_norm, m.in_zone, m.normalization_version, m.measurement_quality, m.created_at
FROM pitches p
LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
WHERE p.pitcher_athlete_id = $1
  AND ($3::text IS NULL OR p.pitch_type = $3)
  AND ($4::text IS NULL OR p.actual_outcome = $4)
  AND ($5::timestamptz IS NULL OR p.thrown_at >= $5)
  AND ($6::timestamptz IS NULL OR p.thrown_at <= $6)
  AND ($7::real IS NULL OR m.release_speed >= $7)
  AND ($8::real IS NULL OR m.release_speed <= $8)
  AND ($9::timestamptz IS NULL
       OR (p.thrown_at, p.id) < ($9::timestamptz, $10::uuid))
ORDER BY p.thrown_at DESC, p.id DESC
LIMIT $2
`

type ListPitchesByPitcherParams struct {
	PitcherAthleteID uuid.UUID
	Limit            int32
	PitchType        *string
	Outcome          *string
	FromTs           *time.Time
	ToTs             *time.Time
	MinSpeed         *float32
	MaxSpeed         *float32
	CursorThrown     *time.Time
	CursorID         *uuid.UUID
}

type ListPitchesByPitcherRow struct {
	Pitch            Pitch
	PitchMeasurement PitchMeasurement
}

// pitcher_athlete_id is required by the API, not optional: without it this
// becomes a sequential scan over millions of rows. Cheaper to make the
// expensive query impossible than to optimize it later.
func (q *Queries) ListPitchesByPitcher(ctx context.Context, arg ListPitchesByPitcherParams) ([]ListPitchesByPitcherRow, error) {
	rows, err := q.db.Query(ctx, listPitchesByPitcher,
		arg.PitcherAthleteID,
		arg.Limit,
		arg.PitchType,
		arg.Outcome,
		arg.FromTs,
		arg.ToTs,
		arg.MinSpeed,
		arg.MaxSpeed,
		arg.CursorThrown,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPitchesByPitcherRow{}
	for rows.Next() {
		var i ListPitchesByPitcherRow
		if err := rows.Scan(
			&i.Pitch.ID,
			&i.Pitch.ExternalPitchUid,
			&i.Pitch.SessionID,
			&i.Pitch.PitcherAthleteID,
			&i.Pitch.BatterAthleteID,
			&i.Pitch.AtBatNumber,
			&i.Pitch.PitchNumber,
			&i.Pitch.SessionPitchIndex,
			&i.Pitch.ThrownAt,
			&i.Pitch.Balls,
			&i.Pitch.Strikes,
			&i.Pitch.OutsWhenUp,
			&i.Pitch.Inning,
			&i.Pitch.InningTopbot,
			&i.Pitch.Stand,
			&i.Pitch.PThrows,
			&i.Pitch.On1b,
			&i.Pitch.On2b,
			&i.Pitch.On3b,
			&i.Pitch.BatScore,
			&i.Pitch.FldScore,
			&i.Pitch.NThruorderPitcher,
			&i.Pitch.PitchType,
			&i.Pitch.PitchName,
			&i.Pitch.ActualOutcome,
			&i.Pitch.PredictionStatus,
			&i.Pitch.CorrelationID,
			&i.Pitch.SourceEventID,
			&i.Pitch.CreatedAt,
			&i.PitchMeasurement.PitchID,
			&i.PitchMeasurement.DeviceID,
			&i.PitchMeasurement.ReleaseSpeed,
			&i.PitchMeasurement.ReleaseSpinRate,
			&i.PitchMeasurement.SpinAxis,
			&i.PitchMeasurement.ReleasePosX,
			&i.PitchMeasurement.ReleasePosY,
			&i.PitchMeasurement.ReleasePosZ,
			&i.PitchMeasurement.ReleaseExtension,
			&i.PitchMeasurement.PfxX,
			&i.PitchMeasurement.PfxZ,
			&i.PitchMeasurement.PlateX,
			&i.PitchMeasurement.PlateZ,
			&i.PitchMeasurement.SzTop,
			&i.PitchMeasurement.SzBot,
			&i.PitchMeasurement.EffectiveSpeed,
			&i.PitchMeasurement.ArmAngle,
			&i.PitchMeasurement.PfxXArm,
			&i.PitchMeasurement.ReleasePosXArm,
			&i.PitchMeasurement.PlateXBat,
			&i.PitchMeasurement.ZoneHeightNorm,
			&i.PitchMeasurement.InZone,
			&i.PitchMeasurement.NormalizationVersion,
			&i.PitchMeasurement.MeasurementQuality,
			&i.PitchMeasurement.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPitchesBySession = `-- name: ListPitchesBySession :many
SELECT
    p.id, p.external_pitch_uid, p.session_id, p.pitcher_athlete_id, p.batter_athlete_id, p.at_bat_number, p.pitch_number, p.session_pitch_index, p.thrown_at, p.balls, p.strikes, p.outs_when_up, p.inning, p.inning_topbot, p.stand, p.p_throws, p.on_1b, p.on_2b, p.on_3b, p.bat_score, p.fld_score, p.n_thruorder_pitcher, p.pitch_type, p.pitch_name, p.actual_outcome, p.prediction_status, p.correlation_id, p.source_event_id, p.created_at,
    m.pitch_id, m.device_id, m.release_speed, m.release_spin_rate, m.spin_axis, m.release_pos_x, m.release_pos_y, m.release_pos_z, m.release_extension, m.pfx_x, m.pfx_z, m.plate_x, m.plate_z, m.sz_top, m.sz_bot, m.effective_speed, m.arm_angle, m.pfx_x_arm, m.release_pos_x_arm, m.plate_x_bat, m.zone_height_norm, m.in_zone, m.normalization_version, m.measurement_quality, m.created_at
FROM pitches p
LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
WHERE p.session_id = $1
  AND ($3::int IS NULL
       OR p.session_pitch_index > $3::int)
ORDER BY p.session_pitch_index
LIMIT $2
`

type ListPitchesBySessionParams struct {
	SessionID   uuid.UUID
	Limit       int32
	CursorIndex *int32
}

type ListPitchesBySessionRow struct {
	Pitch            Pitch
	PitchMeasurement PitchMeasurement
}

// The session timeline, and the opening snapshot for a live WebSocket
// connection. Served by ix_pitches_session_seq.
func (q *Queries) ListPitchesBySession(ctx context.Context, arg ListPitchesBySessionParams) ([]ListPitchesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listPitchesBySession, arg.SessionID, arg.Limit, arg.CursorIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPitchesBySessionRow{}
	for rows.Next() {
		var i ListPitchesBySessionRow
		if err := rows.Scan(
			&i.Pitch.ID,
			&i.Pitch.ExternalPitchUid,
			&i.Pitch.SessionID,
			&i.Pitch.PitcherAthleteID,
			&i.Pitch.BatterAthleteID,
			&i.Pitch.AtBatNumber,
			&i.Pitch.PitchNumber,
			&i.Pitch.SessionPitchIndex,
			&i.Pitch.ThrownAt,
			&i.Pitch.Balls,
			&i.Pitch.Strikes,
			&i.Pitch.OutsWhenUp,
			&i.Pitch.Inning,
			&i.Pitch.InningTopbot,
			&i.Pitch.Stand,
			&i.Pitch.PThrows,
			&i.Pitch.On1b,
			&i.Pitch.On2b,
			&i.Pitch.On3b,
			&i.Pitch.BatScore,
			&i.Pitch.FldScore,
			&i.Pitch.NThruorderPitcher,
			&i.Pitch.PitchType,
			&i.Pitch.PitchName,
			&i.Pitch.ActualOutcome,
			&i.Pitch.PredictionStatus,
			&i.Pitch.CorrelationID,
			&i.Pitch.SourceEventID,
			&i.Pitch.CreatedAt,
			&i.PitchMeasurement.PitchID,
			&i.PitchMeasurement.DeviceID,
			&i.PitchMeasurement.ReleaseSpeed,
			&i.PitchMeasurement.ReleaseSpinRate,
			&i.PitchMeasurement.SpinAxis,
			&i.PitchMeasurement.ReleasePosX,
			&i.PitchMeasurement.ReleasePosY,
			&i.PitchMeasurement.ReleasePosZ,
			&i.PitchMeasurement.ReleaseExtension,
			&i.PitchMeasurement.PfxX,
			&i.PitchMeasurement.PfxZ,
			&i.PitchMeasurement.PlateX,
			&i.PitchMeasurement.PlateZ,
			&i.PitchMeasurement.SzTop,
			&i.PitchMeasurement.SzBot,
			&i.PitchMeasurement.EffectiveSpeed,
			&i.PitchMeasurement.ArmAngle,
			&i.PitchMeasurement.PfxXArm,
			&i.PitchMeasurement.ReleasePosXArm,
			&i.PitchMeasurement.PlateXBat,
			&i.PitchMeasurement.ZoneHeightNorm,
			&i.PitchMeasurement.InZone,
			&i.PitchMeasurement.NormalizationVersion,
			&i.PitchMeasurement.MeasurementQuality,
			&i.PitchMeasurement.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPitchesBySessionDesc = `-- name: ListPitchesBySessionDesc :many
SELECT
    p.id, p.external_pitch_uid, p.session_id, p.pitcher_athlete_id, p.batter_athlete_id, p.at_bat_number, p.pitch_number, p.session_pitch_index, p.thrown_at, p.balls, p.strikes, p.outs_when_up, p.inning, p.inning_topbot, p.stand, p.p_throws, p.on_1b, p.on_2b, p.on_3b, p.bat_score, p.fld_score, p.n_thruorder_pitcher, p.pitch_type, p.pitch_name, p.actual_outcome, p.prediction_status, p.correlation_id, p.source_event_id, p.created_at,
    m.pitch_id, m.device_id, m.release_speed, m.release_spin_rate, m.spin_axis, m.release_pos_x, m.release_pos_y, m.release_pos_z, m.release_extension, m.pfx_x, m.pfx_z, m.plate_x, m.plate_z, m.sz_top, m.sz_bot, m.effective_speed, m.arm_angle, m.pfx_x_arm, m.release_pos_x_arm, m.plate_x_bat, m.zone_height_norm, m.in_zone, m.normalization_version, m.measurement_quality, m.created_at
FROM pitches p
LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
WHERE p.session_id = $1
  AND ($3::int IS NULL
       OR p.session_pitch_index < $3::int)
ORDER BY p.session_pitch_index DESC
LIMIT $2
`

type ListPitchesBySessionDescParams struct {
	SessionID   uuid.UUID
	Limit       int32
	CursorIndex *int32
}

type ListPitchesBySessionDescRow struct {
	Pitch            Pitch
	PitchMeasurement PitchMeasurement
}

func (q *Queries) ListPitchesBySessionDesc(ctx context.Context, arg ListPitchesBySessionDescParams) ([]ListPitchesBySessionDescRow, error) {
	rows, err := q.db.Query(ctx, listPitchesBySessionDesc, arg.SessionID, arg.Limit, arg.CursorIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPitchesBySessionDescRow{}
	for rows.Next() {
		var i ListPitchesBySessionDescRow
		if err := rows.Scan(
			&i.Pitch.ID,
			&i.Pitch.ExternalPitchUid,
			&i.Pitch.SessionID,
			&i.Pitch.PitcherAthleteID,
			&i.Pitch.BatterAthleteID,
			&i.Pitch.AtBatNumber,
			&i.Pitch.PitchNumber,
			&i.Pitch.SessionPitchIndex,
			&i.Pitch.ThrownAt,
			&i.Pitch.Balls,
			&i.Pitch.Strikes,
			&i.Pitch.OutsWhenUp,
			&i.Pitch.Inning,
			&i.Pitch.InningTopbot,
			&i.Pitch.Stand,
			&i.Pitch.PThrows,
			&i.Pitch.On1b,
			&i.Pitch.On2b,
			&i.Pitch.On3b,
			&i.Pitch.BatScore,
			&i.Pitch.FldScore,
			&i.Pitch.NThruorderPitcher,
			&i.Pitch.PitchType,
			&i.Pitch.PitchName,
			&i.Pitch.ActualOutcome,
			&i.Pitch.PredictionStatus,
			&i.Pitch.CorrelationID,
			&i.Pitch.SourceEventID,
			&i.Pitch.CreatedAt,
			&i.PitchMeasurement.PitchID,
			&i.PitchMeasurement.DeviceID,
			&i.PitchMeasurement.ReleaseSpeed,
			&i.PitchMeasurement.ReleaseSpinRate,
			&i.PitchMeasurement.SpinAxis,
			&i.PitchMeasurement.ReleasePosX,
			&i.PitchMeasurement.ReleasePosY,
			&i.PitchMeasurement.ReleasePosZ,
			&i.PitchMeasurement.ReleaseExtension,
			&i.PitchMeasurement.PfxX,
			&i.PitchMeasurement.PfxZ,
			&i.PitchMeasurement.PlateX,
			&i.PitchMeasurement.PlateZ,
			&i.PitchMeasurement.SzTop,
			&i.PitchMeasurement.SzBot,
			&i.PitchMeasurement.EffectiveSpeed,
			&i.PitchMeasurement.ArmAngle,
			&i.PitchMeasurement.PfxXArm,
			&i.PitchMeasurement.ReleasePosXArm,
			&i.PitchMeasurement.PlateXBat,
			&i.PitchMeasurement.ZoneHeightNorm,
			&i.PitchMeasurement.InZone,
			&i.PitchMeasurement.NormalizationVersion,
			&i.PitchMeasurement.MeasurementQuality,
			&i.PitchMeasurement.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSessionPitchIndex = `-- name: NextSessionPitchIndex :one
SELECT COALESCE(max(session_pitch_index), 0) + 1 AS next_index
FROM pitches WHERE session_id = $1
`

// Sequence number within the outing. Safe because a session maps to one
// Kafka partition and a partition is consumed by a single goroutine, so
// writes for one session are serialized by construction.
func (q *Queries) NextSessionPitchIndex(ctx context.Context, sessionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSessionPitchIndex, sessionID)
	var next_index int32
	err := row.Scan(&next_index)
	return next_index, err
}

const setPitchPredictionStatus = `-- name: SetPitchPredictionStatus :exec
UPDATE pitches SET prediction_status = $2 WHERE id = $1
`

type SetPitchPredictionStatusParams struct {
	ID               uuid.UUID
	PredictionStatus string
}

func (q *Queries) SetPitchPredictionStatus(ctx context.Context, arg SetPitchPredictionStatusParams) error {
	_, err := q.db.Exec(ctx, setPitchPredictionStatus, arg.ID, arg.PredictionStatus)
	return err
}
