// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Idempotent: a second call returns no row, which is how the handler
	// distinguishes "already acknowledged" from "not found".
	AcknowledgeAnomaly(ctx context.Context, id uuid.UUID) (PerformanceAnomaly, error)
	// Terminal transition. The WHERE clause makes it idempotent and makes a
	// second attempt distinguishable: no row returned means it was already closed.
	CloseSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Tells you whether a re-normalization pass finished, or left the table
	// holding two conventions at once.
	CountMeasurementsByNormalizationVersion(ctx context.Context) ([]CountMeasurementsByNormalizationVersionRow, error)
	// Served by the partial index ix_anomaly_open.
	CountOpenAnomalies(ctx context.Context, athleteID uuid.UUID) (int64, error)
	// Step one of activation. Must run in the same transaction as step two.
	DeactivateModelVariant(ctx context.Context, variant string) error
	// Tracing support: resolve a correlation id seen in logs back to the pitch.
	FindPitchByCorrelationID(ctx context.Context, correlationID *uuid.UUID) ([]Pitch, error)
	GetActiveModelVersion(ctx context.Context, variant string) (ModelVersion, error)
	GetActivePredictionsForPitch(ctx context.Context, pitchID uuid.UUID) ([]GetActivePredictionsForPitchRow, error)
	// Batched form of GetActivePredictionsForPitch.
	//
	// The per-pitch query is an N+1 waiting to happen: a 100-pitch timeline page
	// would issue 100 round trips. One query with an array parameter issues one.
	GetActivePredictionsForPitches(ctx context.Context, pitchIds []uuid.UUID) ([]GetActivePredictionsForPitchesRow, error)
	GetAnomaly(ctx context.Context, id uuid.UUID) (PerformanceAnomaly, error)
	// Trailing per-session medians for one pitcher and pitch type, newest first.
	//
	// This feeds the robust z-score: median and MAD over the previous N sessions.
	// Median rather than mean, and MAD rather than standard deviation, because a
	// single injury outing inside the window would otherwise inflate sigma and
	// mask every later real anomaly.
	// Thin outings are a noisy baseline; better to have fewer, sounder points.
	GetAnomalyBaselineWindow(ctx context.Context, arg GetAnomalyBaselineWindowParams) ([]GetAnomalyBaselineWindowRow, error)
	GetAthlete(ctx context.Context, id uuid.UUID) (Athlete, error)
	GetAthleteByMLBAMID(ctx context.Context, mlbamID int32) (Athlete, error)
	// Arsenal breakdown. Served by ix_pitches_pitcher_type.
	GetAthletePitchTypeDistribution(ctx context.Context, arg GetAthletePitchTypeDistributionParams) ([]GetAthletePitchTypeDistributionRow, error)
	// Per-outing series behind the performance trend chart.
	GetAthleteSessionTrend(ctx context.Context, arg GetAthleteSessionTrendParams) ([]GetAthleteSessionTrendRow, error)
	// The KPI strip on the athlete overview page. Expensive enough to be worth
	// caching in Redis; correct enough to be the fallback when the cache is cold
	// or unavailable.
	//
	// Every aggregate is wrapped in COALESCE and cast explicitly. Two reasons:
	// sqlc infers a bare aggregate as non-nullable, which panics when scanning
	// the NULL an empty group produces, and it mis-infers the integer division
	// guard as an integer type. The handler suppresses these values when
	// pitch_count is zero, which is the only case where the zero is a lie.
	GetAthleteSummary(ctx context.Context, arg GetAthleteSummaryParams) (GetAthleteSummaryRow, error)
	// first_pitch_at and last_pitch_at are genuinely NULL for an athlete with no
	// pitches. They are left uncast: an explicit ::timestamptz makes sqlc emit a
	// non-pointer time.Time, which then fails at scan time on exactly the rows
	// that need handling. The interface{} sqlc infers is converted in the handler.
	GetAthleteTotals(ctx context.Context, pitcherAthleteID uuid.UUID) (GetAthleteTotalsRow, error)
	GetDeviceByKey(ctx context.Context, deviceKey string) (Device, error)
	GetModelVersion(ctx context.Context, id uuid.UUID) (ModelVersion, error)
	GetPitch(ctx context.Context, id uuid.UUID) (Pitch, error)
	GetPitchByExternalUID(ctx context.Context, externalPitchUid string) (Pitch, error)
	GetPitchMeasurement(ctx context.Context, pitchID uuid.UUID) (PitchMeasurement, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByExternalUID(ctx context.Context, externalSessionUid string) (Session, error)
	// The session under evaluation, shaped like one row of the baseline window.
	GetSessionMetricMedians(ctx context.Context, arg GetSessionMetricMediansParams) (GetSessionMetricMediansRow, error)
	GetSessionOutcomeDistribution(ctx context.Context, sessionID uuid.UUID) ([]GetSessionOutcomeDistributionRow, error)
	// Idempotent via the unique index on
	// (session_id, metric, COALESCE(pitch_type, ''), detector_version).
	// COALESCE is not cosmetic: NULL <> NULL in a plain unique constraint, so
	// without it the rows that most need protection -- those with no pitch type --
	// would duplicate freely on a re-consumed event.
	InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) (PerformanceAnomaly, error)
	InsertModelVersion(ctx context.Context, arg InsertModelVersionParams) (ModelVersion, error)
	// The idempotency boundary of the whole pipeline.
	//
	// Kafka delivers at least once, so this insert will see the same pitch twice
	// whenever a consumer dies between doing its work and committing its offset.
	// DO NOTHING plus the unique constraint on external_pitch_uid makes that
	// harmless, and returning no row is how the caller learns it was a duplicate.
	//
	// An application-level select-then-insert would race between processor
	// instances; the constraint is atomic regardless of concurrency.
	InsertPitch(ctx context.Context, arg InsertPitchParams) (Pitch, error)
	// Served by the partial index ix_sessions_status_started, which stays tiny
	// because active sessions are a negligible fraction of the table.
	ListActiveSessions(ctx context.Context, limit int32) ([]Session, error)
	ListAnomaliesByAthlete(ctx context.Context, arg ListAnomaliesByAthleteParams) ([]PerformanceAnomaly, error)
	ListAnomaliesBySession(ctx context.Context, sessionID uuid.UUID) ([]PerformanceAnomaly, error)
	// Keyset pagination on (full_name, id): offsets shift as rows are inserted,
	// which would repeat or skip records in a continuously growing table.
	ListAthletes(ctx context.Context, arg ListAthletesParams) ([]ListAthletesRow, error)
	ListDevices(ctx context.Context) ([]Device, error)
	// Backfill after an ML outage. Served by the partial index
	// ix_pitches_pred_failed, which is negligible in size because these rows are
	// expected to be a fraction of a percent.
	ListFailedPredictionPitches(ctx context.Context, limit int32) ([]Pitch, error)
	ListModelVersions(ctx context.Context, arg ListModelVersionsParams) ([]ModelVersion, error)
	// pitcher_athlete_id is required by the API, not optional: without it this
	// becomes a sequential scan over millions of rows. Cheaper to make the
	// expensive query impossible than to optimize it later.
	ListPitchesByPitcher(ctx context.Context, arg ListPitchesByPitcherParams) ([]ListPitchesByPitcherRow, error)
	// The session timeline, and the opening snapshot for a live WebSocket
	// connection. Served by ix_pitches_session_seq.
	ListPitchesBySession(ctx context.Context, arg ListPitchesBySessionParams) ([]ListPitchesBySessionRow, error)
	ListPitchesBySessionDesc(ctx context.Context, arg ListPitchesBySessionDescParams) ([]ListPitchesBySessionDescRow, error)
	ListPredictionsForPitch(ctx context.Context, arg ListPredictionsForPitchParams) ([]ListPredictionsForPitchRow, error)
	// Served by ix_sessions_pitcher_started: the composite index covers both the
	// filter and the ordering, so there is no sort step.
	ListSessionsByAthlete(ctx context.Context, arg ListSessionsByAthleteParams) ([]Session, error)
	// Step two of activation.
	//
	// This was first written as a single statement with a data-modifying CTE that
	// deactivated the incumbent before activating the successor. It does not work:
	// in PostgreSQL every CTE and the outer statement see the same snapshot and
	// run concurrently, so the deactivation is invisible to the activation and the
	// partial unique index on (variant) WHERE is_active rejects the write. An
	// integration test caught it.
	//
	// Two statements in one transaction is the correct shape: the second sees the
	// first, and the unique index still makes two concurrent activations
	// impossible rather than merely unlikely -- one of them fails.
	MarkModelVersionActive(ctx context.Context, id uuid.UUID) (ModelVersion, error)
	// Sequence number within the outing. Safe because a session maps to one
	// Kafka partition and a partition is consumed by a single goroutine, so
	// writes for one session are serialized by construction.
	NextSessionPitchIndex(ctx context.Context, sessionID uuid.UUID) (int32, error)
	// Refreshes the denormalized counters from the underlying rows.
	//
	// The averages on `sessions` exist so the session-list page does not run one
	// aggregate per row. Recomputing from source (rather than incrementing) means
	// a replayed or repaired session converges on the truth instead of drifting,
	// and pitch_count cross-checks the rest.
	RecomputeSessionAggregates(ctx context.Context, id uuid.UUID) (Session, error)
	SetPitchPredictionStatus(ctx context.Context, arg SetPitchPredictionStatusParams) error
	// Idempotent by mlbam_id. The event stream re-announces the same athlete on
	// every pitch, so this must converge rather than accumulate. Name and
	// handedness are refreshed; created_at is not touched.
	UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) (Athlete, error)
	// Idempotent by device_key. The replay simulator registers itself on every
	// run, which is how simulated rows stay distinguishable from real ones.
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// Keyed on pitch_id, so re-processing a pitch replaces its measurement rather
	// than duplicating it. The update path is also what a re-normalization pass
	// uses: it rewrites the derived columns and bumps normalization_version
	// without touching the pitch's context row.
	UpsertPitchMeasurement(ctx context.Context, arg UpsertPitchMeasurementParams) (PitchMeasurement, error)
	// Idempotent on (pitch, model version): re-processing the same pitch with the
	// same model must not produce a second row. Values are refreshed rather than
	// ignored, so a re-run after a bug fix corrects the stored prediction.
	UpsertPitchPrediction(ctx context.Context, arg UpsertPitchPredictionParams) (PitchPrediction, error)
	// Idempotent by external_session_uid. Replaying the same outing twice must
	// reuse the session rather than create a second one.
	UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
