// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeSession = `-- name: CloseSession :one
UPDATE sessions
SET status = 'COMPLETED', ended_at = COALESCE(ended_at, now()), updated_at = now()
WHERE id = $1 AND status = 'ACTIVE'
RETURNING id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at
`

// Terminal transition. The WHERE clause makes it idempotent and makes a
// second attempt distinguishable: no row returned means it was already closed.
func (q *Queries) CloseSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, closeSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalSessionUid,
		&i.PitcherAthleteID,
		&i.DeviceID,
		&i.ExternalGameRef,
		&i.SourceGameDate,
		&i.OpponentTeam,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.IsSynthetic,
		&i.PitchCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgPitchScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalSessionUid,
		&i.PitcherAthleteID,
		&i.DeviceID,
		&i.ExternalGameRef,
		&i.SourceGameDate,
		&i.OpponentTeam,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.IsSynthetic,
		&i.PitchCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgPitchScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByExternalUID = `-- name: GetSessionByExternalUID :one
SELECT id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at FROM sessions WHERE external_session_uid = $1
`

func (q *Queries) GetSessionByExternalUID(ctx context.Context, externalSessionUid string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByExternalUID, externalSessionUid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalSessionUid,
		&i.PitcherAthleteID,
		&i.DeviceID,
		&i.ExternalGameRef,
		&i.SourceGameDate,
		&i.OpponentTeam,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.IsSynthetic,
		&i.PitchCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgPitchScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionOutcomeDistribution = `-- name: GetSessionOutcomeDistribution :many
SELECT actual_outcome, count(*) AS n
FROM pitches
WHERE session_id = $1 AND actual_outcome IS NOT NULL
GROUP BY actual_outcome
`

type GetSessionOutcomeDistributionRow struct {
	ActualOutcome *string
	N             int64
}

func (q *Queries) GetSessionOutcomeDistribution(ctx context.Context, sessionID uuid.UUID) ([]GetSessionOutcomeDistributionRow, error) {
	rows, err := q.db.Query(ctx, getSessionOutcomeDistribution, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionOutcomeDistributionRow{}
	for rows.Next() {
		var i GetSessionOutcomeDistributionRow
		if err := rows.Scan(&i.ActualOutcome, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at FROM sessions
WHERE status = 'ACTIVE'
ORDER BY started_at DESC
LIMIT $1
`

// Served by the partial index ix_sessions_status_started, which stays tiny
// because active sessions are a negligible fraction of the table.
func (q *Queries) ListActiveSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ExternalSessionUid,
			&i.PitcherAthleteID,
			&i.DeviceID,
			&i.ExternalGameRef,
			&i.SourceGameDate,
			&i.OpponentTeam,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.IsSynthetic,
			&i.PitchCount,
			&i.AvgReleaseSpeed,
			&i.AvgReleaseSpinRate,
			&i.AvgPitchScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByAthlete = `-- name: ListSessionsByAthlete :many
SELECT id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at FROM sessions
WHERE pitcher_athlete_id = $1
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL
       OR (started_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY started_at DESC, id DESC
LIMIT $2
`

type ListSessionsByAthleteParams struct {
	PitcherAthleteID uuid.UUID
	Limit            int32
	Status           *string
	CursorStarted    *time.Time
	CursorID         *uuid.UUID
}

// Served by ix_sessions_pitcher_started: the composite index covers both the
// filter and the ordering, so there is no sort step.
func (q *Queries) ListSessionsByAthlete(ctx context.Context, arg ListSessionsByAthleteParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByAthlete,
		arg.PitcherAthleteID,
		arg.Limit,
		arg.Status,
		arg.CursorStarted,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ExternalSessionUid,
			&i.PitcherAthleteID,
			&i.DeviceID,
			&i.ExternalGameRef,
			&i.SourceGameDate,
			&i.OpponentTeam,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.IsSynthetic,
			&i.PitchCount,
			&i.AvgReleaseSpeed,
			&i.AvgReleaseSpinRate,
			&i.AvgPitchScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recomputeSessionAggregates = `-- name: RecomputeSessionAggregates :one
UPDATE sessions s SET
    pitch_count           = agg.n,
    avg_release_speed     = agg.avg_speed,
    avg_release_spin_rate = agg.avg_spin,
    avg_pitch_score       = agg.avg_score,
    updated_at            = now()
FROM (
    SELECT
        count(*)                    AS n,
        avg(m.release_speed)        AS avg_speed,
        avg(m.release_spin_rate)    AS avg_spin,
        avg(pr.score)               AS avg_score
    FROM pitches p
    LEFT JOIN pitch_measurements m ON m.pitch_id = p.id
    LEFT JOIN pitch_predictions pr ON pr.pitch_id = p.id
         AND pr.model_version_id = (
             SELECT id FROM model_versions
             WHERE variant = 'pitching' AND is_active LIMIT 1
         )
    WHERE p.session_id = $1
) AS agg
WHERE s.id = $1
RETURNING s.id, s.external_session_uid, s.pitcher_athlete_id, s.device_id, s.external_game_ref, s.source_game_date, s.opponent_team, s.started_at, s.ended_at, s.status, s.is_synthetic, s.pitch_count, s.avg_release_speed, s.avg_release_spin_rate, s.avg_pitch_score, s.created_at, s.updated_at
`

// Refreshes the denormalized counters from the underlying rows.
//
// The averages on `sessions` exist so the session-list page does not run one
// aggregate per row. Recomputing from source (rather than incrementing) means
// a replayed or repaired session converges on the truth instead of drifting,
// and pitch_count cross-checks the rest.
func (q *Queries) RecomputeSessionAggregates(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, recomputeSessionAggregates, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalSessionUid,
		&i.PitcherAthleteID,
		&i.DeviceID,
		&i.ExternalGameRef,
		&i.SourceGameDate,
		&i.OpponentTeam,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.IsSynthetic,
		&i.PitchCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgPitchScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (
    id, external_session_uid, pitcher_athlete_id, device_id,
    external_game_ref, source_game_date, opponent_team,
    started_at, status, is_synthetic
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (external_session_uid) DO UPDATE SET
    device_id     = COALESCE(EXCLUDED.device_id, sessions.device_id),
    opponent_team = COALESCE(EXCLUDED.opponent_team, sessions.opponent_team),
    updated_at    = now()
RETURNING id, external_session_uid, pitcher_athlete_id, device_id, external_game_ref, source_game_date, opponent_team, started_at, ended_at, status, is_synthetic, pitch_count, avg_release_speed, avg_release_spin_rate, avg_pitch_score, created_at, updated_at
`

type UpsertSessionParams struct {
	ID                 uuid.UUID
	ExternalSessionUid string
	PitcherAthleteID   uuid.UUID
	DeviceID           *uuid.UUID
	ExternalGameRef    *string
	SourceGameDate     *time.Time
	OpponentTeam       *string
	StartedAt          time.Time
	Status             string
	IsSynthetic        bool
}

// Idempotent by external_session_uid. Replaying the same outing twice must
// reuse the session rather than create a second one.
func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.ID,
		arg.ExternalSessionUid,
		arg.PitcherAthleteID,
		arg.DeviceID,
		arg.ExternalGameRef,
		arg.SourceGameDate,
		arg.OpponentTeam,
		arg.StartedAt,
		arg.Status,
		arg.IsSynthetic,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalSessionUid,
		&i.PitcherAthleteID,
		&i.DeviceID,
		&i.ExternalGameRef,
		&i.SourceGameDate,
		&i.OpponentTeam,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.IsSynthetic,
		&i.PitchCount,
		&i.AvgReleaseSpeed,
		&i.AvgReleaseSpinRate,
		&i.AvgPitchScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
