package processor

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/hkocamandev/pitchlab/internal/events"
	"github.com/hkocamandev/pitchlab/internal/mlclient"
)

// The golden fixture is the highest-value test in this package.
//
// The Go processor and the Python training code both transform raw readings,
// and they have to agree exactly. If they drift, nothing errors -- the model
// simply starts receiving features that mean something slightly different from
// what it was trained on, and every score quietly stops being meaningful.
//
// The fixture is generated by running real pitches through the training-time
// feature code (ml/scripts/export_normalization_fixture.py). Changing
// features.py without regenerating it breaks this test, which is the point.

type goldenFile struct {
	Note           string       `json:"note"`
	SourceSnapshot string       `json:"source_snapshot"`
	Cases          []goldenCase `json:"cases"`
}

type goldenCase struct {
	Input    goldenInput               `json:"input"`
	Expected map[string]*float64OrBool `json:"expected"`
}

type goldenInput struct {
	PThrows   string   `json:"p_throws"`
	Stand     string   `json:"stand"`
	PitchType string   `json:"pitch_type"`
	Speed     *float64 `json:"release_speed"`
	SpinRate  *float64 `json:"release_spin_rate"`
	SpinAxis  *float64 `json:"spin_axis"`
	RelPosX   *float64 `json:"release_pos_x"`
	RelPosZ   *float64 `json:"release_pos_z"`
	Extension *float64 `json:"release_extension"`
	PfxX      *float64 `json:"pfx_x"`
	PfxZ      *float64 `json:"pfx_z"`
	PlateX    *float64 `json:"plate_x"`
	PlateZ    *float64 `json:"plate_z"`
	SzTop     *float64 `json:"sz_top"`
	SzBot     *float64 `json:"sz_bot"`
	ArmAngle  *float64 `json:"arm_angle"`
}

// float64OrBool accepts either, because in_zone is a boolean while everything
// else is numeric.
type float64OrBool struct {
	Num  *float64
	Bool *bool
}

func (v *float64OrBool) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		return nil
	}
	var f float64
	if err := json.Unmarshal(b, &f); err == nil {
		v.Num = &f
		return nil
	}
	var bl bool
	if err := json.Unmarshal(b, &bl); err == nil {
		v.Bool = &bl
		return nil
	}
	return nil
}

func loadGolden(t *testing.T) goldenFile {
	t.Helper()
	path := filepath.Join("testdata", "normalization_golden.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("golden fixture not present; generate it with "+
			"ml/scripts/export_normalization_fixture.py (%v)", err)
	}
	var g goldenFile
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	if len(g.Cases) == 0 {
		t.Fatal("fixture has no cases")
	}
	return g
}

func (in goldenInput) toRaw() events.RawMeasurement {
	return events.RawMeasurement{
		PitchType:        in.PitchType,
		ReleaseSpeed:     in.Speed,
		ReleaseSpinRate:  in.SpinRate,
		SpinAxis:         in.SpinAxis,
		ReleasePosX:      in.RelPosX,
		ReleasePosZ:      in.RelPosZ,
		ReleaseExtension: in.Extension,
		PfxX:             in.PfxX,
		PfxZ:             in.PfxZ,
		PlateX:           in.PlateX,
		PlateZ:           in.PlateZ,
		SzTop:            in.SzTop,
		SzBot:            in.SzBot,
		ArmAngle:         in.ArmAngle,
	}
}

func TestNormalizationMatchesTheTrainingCode(t *testing.T) {
	golden := loadGolden(t)
	const tolerance = 1e-9

	for i, tc := range golden.Cases {
		norm := Normalize(tc.Input.toRaw(), tc.Input.PThrows, tc.Input.Stand)

		check := func(name string, got *float64) {
			t.Helper()
			want, present := tc.Expected[name]
			if !present || want == nil || want.Num == nil {
				if got != nil {
					t.Errorf("case %d (%s vs %s) %s: Go produced %.10f, Python produced nothing",
						i, tc.Input.PThrows, tc.Input.Stand, name, *got)
				}
				return
			}
			if got == nil {
				t.Errorf("case %d (%s vs %s) %s: Go produced nothing, Python produced %.10f",
					i, tc.Input.PThrows, tc.Input.Stand, name, *want.Num)
				return
			}
			if math.Abs(*got-*want.Num) > tolerance {
				t.Errorf("case %d (%s vs %s) %s: Go %.10f, Python %.10f (diff %.2e)",
					i, tc.Input.PThrows, tc.Input.Stand, name, *got, *want.Num,
					math.Abs(*got-*want.Num))
			}
		}

		check("pfx_x_arm", norm.PfxXArm)
		check("release_pos_x_arm", norm.ReleasePosXArm)
		check("plate_x_bat", norm.PlateXBat)
		check("zone_height_norm", norm.ZoneHeightNorm)

		if want, ok := tc.Expected["in_zone"]; ok && want != nil {
			var wantBool *bool
			switch {
			case want.Bool != nil:
				wantBool = want.Bool
			case want.Num != nil:
				b := *want.Num != 0
				wantBool = &b
			}
			if wantBool != nil && norm.InZone != nil && *norm.InZone != *wantBool {
				t.Errorf("case %d in_zone: Go %v, Python %v", i, *norm.InZone, *wantBool)
			}
		}

		// Spin encoding and zone distance are computed in the feature builder
		// rather than the normalizer, so they are checked through it.
		f := BuildFeatures(FeatureInput{
			Measurement: norm,
			Stand:       tc.Input.Stand,
			PThrows:     tc.Input.PThrows,
			PitchType:   tc.Input.PitchType,
		}, mlclient.VariantPitching)

		checkFeature := func(name string) {
			t.Helper()
			want, present := tc.Expected[name]
			if !present || want == nil || want.Num == nil {
				return
			}
			got, ok := f[name].(float64)
			if !ok {
				t.Errorf("case %d %s: Go did not produce the feature, Python produced %.10f",
					i, name, *want.Num)
				return
			}
			if math.Abs(got-*want.Num) > tolerance {
				t.Errorf("case %d (%s vs %s) %s: Go %.10f, Python %.10f",
					i, tc.Input.PThrows, tc.Input.Stand, name, got, *want.Num)
			}
		}
		checkFeature("spin_axis_sin")
		checkFeature("spin_axis_cos")
		checkFeature("dist_from_zone_center")
	}
}

func TestGoldenFixtureCoversBothHandednessCombinations(t *testing.T) {
	// A fixture of only right-on-right pitches would pass with the mirroring
	// inverted, which is exactly the bug that shipped once already.
	golden := loadGolden(t)

	seen := map[string]int{}
	for _, tc := range golden.Cases {
		seen[tc.Input.PThrows+tc.Input.Stand]++
	}
	for _, combo := range []string{"RR", "RL", "LR", "LL"} {
		if seen[combo] == 0 {
			t.Errorf("fixture has no %s pitcher vs %s batter case",
				string(combo[0]), string(combo[1]))
		}
	}
}

// --- the rules, stated directly --------------------------------------------

func f64(v float64) *float64 { return &v }

func TestArmSideIsPositiveForBothHands(t *testing.T) {
	// League means for four-seam fastballs, where the run is by definition to
	// the pitcher's arm side. Consistency alone would pass with the sign
	// inverted; this pins the direction.
	rhp := Normalize(events.RawMeasurement{
		PfxX: f64(-0.63), ReleasePosX: f64(-1.83),
	}, "R", "L")
	lhp := Normalize(events.RawMeasurement{
		PfxX: f64(0.66), ReleasePosX: f64(1.94),
	}, "L", "R")

	if rhp.PfxXArm == nil || *rhp.PfxXArm <= 0 {
		t.Error("right-hander's arm-side run must be positive")
	}
	if lhp.PfxXArm == nil || *lhp.PfxXArm <= 0 {
		t.Error("left-hander's arm-side run must be positive")
	}
	if rhp.ReleasePosXArm == nil || *rhp.ReleasePosXArm <= 0 {
		t.Error("right-hander's release point must be positive in the arm frame")
	}
}

func TestInsideIsPositiveForBothStances(t *testing.T) {
	// Derived from hit-by-pitch locations: right-handed batters are hit at a
	// mean plate_x of -1.94, left-handers at +1.98.
	rhb := Normalize(events.RawMeasurement{PlateX: f64(-0.6)}, "R", "R")
	lhb := Normalize(events.RawMeasurement{PlateX: f64(0.6)}, "R", "L")
	outside := Normalize(events.RawMeasurement{PlateX: f64(0.6)}, "R", "R")

	if rhb.PlateXBat == nil || *rhb.PlateXBat <= 0 {
		t.Error("inside to a right-handed batter must be positive")
	}
	if lhb.PlateXBat == nil || *lhb.PlateXBat <= 0 {
		t.Error("inside to a left-handed batter must be positive")
	}
	if outside.PlateXBat == nil || *outside.PlateXBat >= 0 {
		t.Error("outside must be negative")
	}
}

func TestSpinAxisIsCircular(t *testing.T) {
	// 359 degrees and 1 degree are two degrees apart, not 358.
	sinA, cosA := spinAxisComponents(1, false)
	sinB, cosB := spinAxisComponents(359, false)

	dist := math.Hypot(sinA-sinB, cosA-cosB)
	if dist > 0.05 {
		t.Fatalf("1 and 359 degrees encode %.4f apart", dist)
	}
	if r := math.Hypot(sinA, cosA); math.Abs(r-1) > 1e-9 {
		t.Errorf("encoding is not on the unit circle: radius %.10f", r)
	}

	// Pure backspin and pure topspin must be maximally far apart.
	sinBack, cosBack := spinAxisComponents(180, false)
	sinTop, cosTop := spinAxisComponents(0, false)
	if d := math.Hypot(sinBack-sinTop, cosBack-cosTop); math.Abs(d-2) > 1e-9 {
		t.Errorf("backspin and topspin encode %.4f apart, want 2", d)
	}
}

func TestSpinAxisMirrorsConsistentlyWithMovement(t *testing.T) {
	// Mirror-image pitches must land on the same encoded point.
	rhpSin, rhpCos := spinAxisComponents(120, true)
	lhpSin, lhpCos := spinAxisComponents(240, false)

	if math.Abs(rhpSin-lhpSin) > 1e-9 || math.Abs(rhpCos-lhpCos) > 1e-9 {
		t.Errorf("mirror images encode differently: (%.6f,%.6f) vs (%.6f,%.6f)",
			rhpSin, rhpCos, lhpSin, lhpCos)
	}
}

func TestZoneHeightIsComparableAcrossBatters(t *testing.T) {
	short := Normalize(events.RawMeasurement{
		PlateZ: f64(2.2), SzBot: f64(1.4), SzTop: f64(3.0),
	}, "R", "R")
	tall := Normalize(events.RawMeasurement{
		PlateZ: f64(2.8), SzBot: f64(1.8), SzTop: f64(3.8),
	}, "R", "R")

	if short.ZoneHeightNorm == nil || tall.ZoneHeightNorm == nil {
		t.Fatal("zone height not computed")
	}
	if math.Abs(*short.ZoneHeightNorm-*tall.ZoneHeightNorm) > 1e-9 {
		t.Errorf("same relative height encodes differently: %.6f vs %.6f",
			*short.ZoneHeightNorm, *tall.ZoneHeightNorm)
	}
}

func TestImpossibleReadingsAreNulledNotDropped(t *testing.T) {
	// One bad sensor field must not discard an otherwise usable pitch, and
	// substituting a plausible number would invent a measurement.
	n := Normalize(events.RawMeasurement{
		ReleaseSpeed:    f64(250), // a sensor fault
		ReleaseSpinRate: f64(2400),
		PlateX:          f64(0.3),
	}, "R", "R")

	if n.ReleaseSpeed != nil {
		t.Errorf("250 mph should be nulled, got %.1f", *n.ReleaseSpeed)
	}
	if n.ReleaseSpinRate == nil || *n.ReleaseSpinRate != 2400 {
		t.Error("the rest of the reading should survive")
	}
	if n.MeasurementQuality != "PARTIAL" {
		t.Errorf("quality %q, want PARTIAL", n.MeasurementQuality)
	}
}

func TestMissingMeasurementsStayMissing(t *testing.T) {
	n := Normalize(events.RawMeasurement{ReleaseSpeed: f64(94)}, "R", "R")

	if n.PfxXArm != nil || n.PlateXBat != nil || n.ZoneHeightNorm != nil {
		t.Error("derived values must not be invented from absent inputs")
	}

	f := BuildFeatures(FeatureInput{
		Measurement: n, Stand: "R", PThrows: "R", PitchType: "FF",
	}, mlclient.VariantPitching)

	if _, present := f["pfx_x_arm"]; present {
		t.Error("an absent feature must be omitted, not sent as zero")
	}
	if f["release_speed"] != 94.0 {
		t.Error("a present feature should be sent")
	}
}

func TestUnknownPitchTypeIsACategory(t *testing.T) {
	// Dropping unclassified pitches would bias the data toward whatever the
	// classifier finds easy.
	f := BuildFeatures(FeatureInput{
		Measurement: Normalize(events.RawMeasurement{}, "R", "R"),
		Stand:       "R", PThrows: "R", PitchType: "",
	}, mlclient.VariantPitching)

	if f["pitch_type"] != "UNKNOWN" || f["pitch_group"] != "OTHER" {
		t.Errorf("got %v / %v", f["pitch_type"], f["pitch_group"])
	}
}

func TestStuffVariantSeesNeitherLocationNorSituation(t *testing.T) {
	// StuffScore describes the pitch's shape. Phase 1 measured that scoring
	// stuff on anything else buries it under geometry.
	n := Normalize(events.RawMeasurement{
		ReleaseSpeed: f64(87.4), PfxX: f64(0.71), PfxZ: f64(0.12),
		PlateX: f64(0.34), PlateZ: f64(1.92), SzTop: f64(3.41), SzBot: f64(1.58),
	}, "R", "L")

	in := FeatureInput{
		Measurement: n, Stand: "L", PThrows: "R", PitchType: "SL",
		Context: events.PitchContext{Balls: 1, Strikes: 2, Inning: 5},
	}

	stuff := BuildFeatures(in, mlclient.VariantStuff)
	for _, forbidden := range []string{
		"plate_x_bat", "zone_height_norm", "in_zone", "dist_from_zone_center",
		"balls", "strikes", "count_state", "inning", "runners_state",
		// Sequence and rest are situation, not shape. Sending them cost 228
		// rejected predictions before the contract check caught it.
		"pitch_number", "pitcher_days_since_prev_game",
	} {
		if _, present := stuff[forbidden]; present {
			t.Errorf("the stuff variant must not see %s", forbidden)
		}
	}
	if _, present := stuff["release_speed"]; !present {
		t.Error("the stuff variant must see the pitch's physical shape")
	}

	pitching := BuildFeatures(in, mlclient.VariantPitching)
	for _, required := range []string{"plate_x_bat", "in_zone", "count_state"} {
		if _, present := pitching[required]; !present {
			t.Errorf("the pitching variant should see %s", required)
		}
	}
}

func TestCountAndRunnerEncodings(t *testing.T) {
	if got := CountState(3, 2); got != "3-2" {
		t.Errorf("CountState = %q", got)
	}
	cases := map[string][3]bool{
		"___": {false, false, false},
		"1__": {true, false, false},
		"1_3": {true, false, true},
		"123": {true, true, true},
	}
	for want, in := range cases {
		if got := RunnersState(in[0], in[1], in[2]); got != want {
			t.Errorf("RunnersState(%v) = %q, want %q", in, got, want)
		}
	}
}

func TestFeatureInputCannotCarryAnOutcome(t *testing.T) {
	// The leakage defense in the Go path is the shape of this struct: there
	// is no field for the outcome, so the feature builder cannot be handed
	// one even by accident. pitches.actual_outcome exists and is written --
	// it just never arrives here.
	//
	// This test is a statement of intent that fails if someone adds one.
	var in FeatureInput
	f := BuildFeatures(in, mlclient.VariantPitching)

	for _, leaky := range []string{
		"actual_outcome", "outcome", "description", "events",
		"launch_speed", "launch_angle", "delta_run_exp",
		"estimated_woba_using_speedangle", "bat_speed",
	} {
		if _, present := f[leaky]; present {
			t.Errorf("%s reached the feature vector", leaky)
		}
	}
}
